# Generated by Django 3.2.8 on 2021-11-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avail',
            field=models.BooleanField(default=True),
        ),
    ]
