# Generated by Django 3.2.8 on 2021-11-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_avail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avail',
            field=models.BooleanField(default=False),
        ),
    ]
