# Generated by Django 3.2.8 on 2021-11-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Address',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
